version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tocktalks-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tocktalks
      MYSQL_USER: tocktalks
      MYSQL_PASSWORD: tocktalks
    ports:
      - "3307:3306"
    volumes:
      - tocktalks-mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: tocktalks-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - tocktalks-redis-data:/data

volumes:
  tocktalks-mysql-data:
  tocktalks-redis-data:
